name: 'vanilla_dart'
version: 0.0.1
description: An absolute bare-bones web app.
publish_to: none

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  my_dependency: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  dazel: ">=0.3.0 <0.4.0"

transformers:
- dart_to_js_script_rewriter
